version: "3"
services:
        nginx:
                image: nginx:latest
                ports:
                        - "82:80"
                        - "2443:443"
                volumes:
                        - ./hosts:/etc/nginx/conf.d
                        - ./www:/var/www
                        - ./logs/nginx:/var/log/nginx
                links:
                        - php
        php:
                build: ./php
                volumes:
                        - ./www:/var/www
~                                             
